name: SENSEI • in situ
description: Scalable analysis methods and in situ infrastructure for extreme scale knowledge discovery
url: https://sensei-insitu.org/
logo: images/sensei_logo_small.png
theme: slate
